version: "3.9"

services:

  browser:
    build: ./browser
    container_name: browser
    ports:
      - "4444:4444"
      - "6080:6080"

  runner:
    build: ./runner
    container_name: runner
    depends_on:
      - browser
    stdin_open: true
    tty: true